In [92]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso , Ridge

warnings.filterwarnings('ignore')

In [93]:
df=pd.read_csv('C:\\Data\\Melbourne_housing_FULL.csv')
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

In [94]:
df.nunique()

Suburb             351
Address          34009
Rooms               12
Type                 3
Price             2871
Method               9
SellerG            388
Date                78
Distance           215
Postcode           211
Bedroom2            15
Bathroom            11
Car                 15
Landsize          1684
BuildingArea       740
YearBuilt          160
CouncilArea         33
Lattitude        13402
Longtitude       14524
Regionname           8
Propertycount      342
dtype: int64

In [95]:
col_to_use=df.drop(['Address','Date','YearBuilt','Longtitude','Lattitude','Regionname'],axis=1)
new_df=pd.DataFrame(col_to_use)
new_df.head()

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,3067.0,2.0,1.0,1.0,126.0,NaN,Yarra City Council,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,3067.0,2.0,1.0,1.0,202.0,NaN,Yarra City Council,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,3067.0,2.0,1.0,0.0,156.0,79.0,Yarra City Council,4019.0
3,Abbotsford,3,u,NaN,VB,Rounds,2.5,3067.0,3.0,2.0,1.0,0.0,NaN,Yarra City Council,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3067.0,3.0,2.0,0.0,134.0,150.0,Yarra City Council,4019.0

In [96]:
new_df.isna().sum()

Suburb               0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Distance             1
Postcode             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
CouncilArea          3
Propertycount        3
dtype: int64

In [97]:
cols_to_fill_zero=['Propertycount','Car','Bedroom2','Bathroom','Distance']
new_df[cols_to_fill_zero]=new_df[cols_to_fill_zero].fillna(0)
new_df.isna().sum()

Suburb               0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Distance             0
Postcode             1
Bedroom2             0
Bathroom             0
Car                  0
Landsize         11810
BuildingArea     21115
CouncilArea          3
Propertycount        0
dtype: int64

In [98]:
new_df['Landsize']=new_df['Landsize'].fillna(new_df.Landsize.mean())
new_df['BuildingArea']=new_df['BuildingArea'].fillna(new_df.BuildingArea.mean())
new_df.isna().sum()

Suburb              0
Rooms               0
Type                0
Price            7610
Method              0
SellerG             0
Distance            0
Postcode            1
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
CouncilArea         3
Propertycount       0
dtype: int64

In [99]:
new_df.dropna(inplace=True)
new_df.isna().sum()

Suburb           0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Distance         0
Postcode         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
CouncilArea      0
Propertycount    0
dtype: int64

In [100]:
new_df=pd.get_dummies(new_df,drop_first=True)
new_df

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Propertycount,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
1,2,1480000.0,2.5,3067.0,2.0,1.0,1.0,202.000000,160.2564,4019.0,...,0,0,0,0,0,0,0,0,1,0
2,2,1035000.0,2.5,3067.0,2.0,1.0,0.0,156.000000,79.0000,4019.0,...,0,0,0,0,0,0,0,0,1,0
4,3,1465000.0,2.5,3067.0,3.0,2.0,0.0,134.000000,150.0000,4019.0,...,0,0,0,0,0,0,0,0,1,0
5,3,850000.0,2.5,3067.0,3.0,2.0,1.0,94.000000,160.2564,4019.0,...,0,0,0,0,0,0,0,0,1,0
6,4,1600000.0,2.5,3067.0,3.0,1.0,2.0,120.000000,142.0000,4019.0,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,4,1480000.0,6.3,3013.0,4.0,1.0,3.0,593.000000,160.2564,6543.0,...,0,0,0,0,0,0,0,0,0,0
34853,2,888000.0,6.3,3013.0,2.0,2.0,1.0,98.000000,104.0000,6543.0,...,0,0,0,0,0,0,0,0,0,0
34854,2,705000.0,6.3,3013.0,2.0,1.0,2.0,220.000000,120.0000,6543.0,...,0,0,0,0,0,0,0,0,0,0
34855,3,1140000.0,6.3,3013.0,0.0,0.0,0.0,593.598993,160.2564,6543.0,...,0,0,0,0,0,0,0,0,0,0
34856,2,1020000.0,6.3,3013.0,2.0,1.0,0.0,250.000000,103.0000,6543.0,...,0,0,0,0,0,0,0,0,0,0

In [101]:
x=new_df.drop('Price',axis=1)
y=new_df['Price']

In [102]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2)

In [103]:
model=LinearRegression().fit(x_train,y_train)

In [104]:
print('Model Score (Test Dataset): {} \nModel Score (Train Dataset): {}'.format(model.score(x_test,y_test),model.score(x_train,y_train)))

Model Score (Test Dataset): 0.1385546872247585
Model Score (Train Dataset): 0.6827792395792723

## Lasso Regression (L1 Regularization)

In [105]:
lasso_reg_model=Lasso(alpha=50,max_iter=100,tol=0.1)
lasso_reg_model.fit(x_train,y_train)

Lasso(alpha=50, max_iter=100, tol=0.1)

In [106]:
print('Lasso-\nModel Score (Test Dataset): {} \nModel Score (Train Dataset): {}'.format(lasso_reg_model.score(x_test,y_test),lasso_reg_model.score(x_train,y_train)))

Lasso-
Model Score (Test Dataset): 0.6643776414608696
Model Score (Train Dataset): 0.6766752210708142

## Ridge Regression (L2 Regularization)

In [107]:
ridge_reg_model=Ridge(alpha=50,max_iter=100,tol=0.1)
ridge_reg_model.fit(x_train,y_train)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [108]:
print('Ridge-\nModel Score (Test Dataset): {} \nModel Score (Train Dataset): {}'.format(ridge_reg_model.score(x_test,y_test),ridge_reg_model.score(x_train,y_train)))

Ridge-
Model Score (Test Dataset): 0.66665602533032
Model Score (Train Dataset): 0.6619891153780934